services:
  beszel:
    container_name: beszel
    image: henrygd/beszel:latest
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - /srv/docker/volumes/beszel:/data
    networks:
      - dokploy-network
    environment:
      - APP_URL=${APP_URL}

  beszel-agent:
    container_name: beszel-agent
    image: henrygd/beszel-agent:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PORT: ${AGENT_PORT}
      KEY: ${AGENT_KEY}
      HUB_URL: ${HUB_URL}
      TOKEN: ${AGENT_TOKEN}

networks:
  dokploy-network:
    external: true
    name: dokploy-network
